### ISSUE TITLE
Change CORS settings in Symfony to allow UI access from various ports

### ISSUE THREAD

**Issue by baddlan** [DigitalState/Platform#2]
In order to avoid errors like:
```
[Error] Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin. (admin, line 0)
[Error] XMLHttpRequest cannot load http://localhost:8010/app_dev.php/tokens/admin due to access control checks.
```
The `app/config/dev/parameters.dist.yml` needs to have `cors_allow_origin` set to `'*'`.

**Comment by StephenOTT** [comment]
Updates have been made to Auth, Identities, and Services Microserivices.  Further updates will be made in coming days to the rest of the platform's microservices

cc: @mario-digitalstate
