### ISSUE TITLE
Error 401 when trying to get an authorization token

### ISSUE THREAD

**Issue by kmbuco** [DigitalState/Platform#26]
Am trying to send a request from Post man to get a token for the staff user. It is returning a 401 for this request. Below I have attached the image showing the error.

![gettoken request](https://user-images.githubusercontent.com/3265054/36344337-fe60103c-1429-11e8-9c57-16bf6ff249b9.PNG)

**Comment by kmbuco** [comment]
I get the below error when I try to get a token for anonymous.

![image](https://user-images.githubusercontent.com/3265054/36344554-8fb5fa3a-142d-11e8-8ad2-855c7b2483db.png)

**Comment by kmbuco** [comment]
in postgres i get the below

> postgres=# \c authentication
> You are now connected to database "authentication" as user "postgres".
> authentication=# \dt
> No relations found.
> authentication=#

**Comment by marioprudhomme** [comment]
I've found the issue. The ansible playbooks for database migration and fixtures weren't being executed correctly under Alpine. I've updated the SDK code 4f9468321613ce99d79b20f80feea41feab35283

The issue you are seeing is the fact that the database schema doesn't exists.

**Comment by kmbuco** [comment]
@mario-digitalstate I want to update this changes without doing a clean and build on the images already existing. Is there a way of updating the necessary images without doing a clean install?

**Comment by marioprudhomme** [comment]
Yes. Simply pull in the latest sdk code (git pull). This can be done while the SDK container is up and running without issues.
Once you have the fix on your local computer, resume the playbooks commands from here  https://github.com/DigitalState/Sdk/blob/master/sdk/ansible/env/lab/deploy.yml#L10

```
ansible-playbook ./database/migration/load.yml
ansible-playbook ./import_playbook: database/fixtures/load.yml
ansible-playbook ./config/api/configure.yml
ansible-playbook ./util/adminer/download.yml
```

**Comment by marioprudhomme** [comment]
Please try v0.5.0 with latest documentation. If the problem persists, feel free to re-open the issue.
