### ISSUE TITLE
Error installing SDK at TASK [app/camunda/container/up : Up camunda container] 

### ISSUE THREAD

**Issue by gavinjolly** [DigitalState/Platform#27]
Trying to install on a Windows 10 laptop. I am further than my previous attempt at starting the ASSETS container. 

JIC it is relevant I used PuttyGEN to generate the keys. 
- The app path is ```C:\Users\gjolly\workspaces\digitalstate\app```
- Directory is set to ```directory: /C/Users/gjolly/workspaces/digitalstate/app```

                                                                                                                                                                            
```
TASK [app/camunda/container/up : Up camunda container] 
*************************************************************************************************************************************
fatal: [server]: FAILED! => {"changed": false, "errors": [], "module_stderr": "", "module_stdout": "Step 1/18 : FROM camunda/camunda-bpm-platform:tomcat-7.8.0\n", "msg":
"Error starting project unknown cause"}                                                                                                                                            *********
PLAY RECAP *********************************************************************************************************************************************************************************
sdk                        : ok=191  changed=0    unreachable=0    failed=0
server                     : ok=190  changed=75   unreachable=0    failed=1
```

Other Details
```
PS C:\Users\gjolly\workspaces\digitalstate\sdk> docker versionClient:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true
```

**Comment by marioprudhomme** [comment]
I have a feeling it has to do with de-synchronized versions of repositories and the sdk. (Not all develop branches were compatible across the board at different points in time)

I have focused the past few days on tagging all the repositories and the SDK at 0.1.0. I still have to run tests at the application level to stabilize everything. However, the SDK deployment works currently on my machine (windows 10 pro) with the tags.

I suggest resetting DockerForWindows at Factory defaults, re-download the SDK and run the tutorial at https://github.com/DigitalState/Sdk/blob/master/sdk/documentation/lab/index.md

Let us know if there are other issues.

**Comment by marioprudhomme** [comment]
Forgot to mention, use SDK 0.1.0 and not master branch.

**Comment by marioprudhomme** [comment]
Please try v0.5.0 with latest documentation. If the problem persists, feel free to re-open the issue.
