### ISSUE TITLE
platform launched but no app available (0.7 related)

### ISSUE THREAD

**Issue by gismomtl** [DigitalState/Platform#34]
Hi, 
the docker is started, install script completed and 51 dockers apps started.
However when trying to connect to the URL:
- for formio, http://api.formio.lab.ds/ error 503
- for http://admin.lab.ds/ and http://portal.lab.ds/, the 3 color lines are looping and message "error while requesting anonymous token" but nothing
 how to solve that?

BTW, is there a way to stop / start all docker created without going the install process ?

**Comment by gismomtl** [comment]
with tag 0.7.0 , formio is now working compared to master release ... but lab.ds portal and admin are not with the same error.
I only updated the app parameter in lab/inventory.yml file.

**Comment by StephenOTT** [comment]
The default Portal and admin UI are broken in 0.7 due to rapid releases of tenants support and updated security due to tenants. 

If you deploy 0.6 you should be okay

**Comment by StephenOTT** [comment]
Also make sure to check the instructions page for 0.6 as the steps may have changed

**Comment by StephenOTT** [comment]
For your formio issue, this was caused by the 0.7 update having a new microservice added to front the formio service.  See: https://github.com/DigitalState/Platform/issues/35

Move to tag 0.6 if you want to use the UI at this time.

**Comment by gismomtl** [comment]
tried with 0.6 but still  getting "error while requesting anonymous token" message.
I will try again by flushing all docker images just in case of remaining data from other version...

**Comment by gismomtl** [comment]
no luck :(

**Comment by StephenOTT** [comment]
You are using the postman collection provided in the platform repo? 

What are the steps are you following?

**Comment by marioprudhomme** [comment]
The playbooks structure changed a bit between 0.6 and 0.7, but to restart containers without a full reinstall: `ansible-playbook app/container/up.yml`.

There's also `down.yml` and `stop.yml`.

You can also supply a tag: `ansible-playbook app/container/up.yml --tags="authentication"` to only affect certain containers.

**Comment by Illusive7Man** [comment]
I got the same issue and I had  followed [Lab Environment](https://github.com/DigitalState/Platform/blob/develop/platform/documentation/environments/lab/index.md) setup, that is, I modified inventory.yml values to:
 **encryption.secret**: 11111111111111111111111111111111
 **jwt.pass_phrase**: 1111
 **directory**: /c/Users/illus/DockerProjects/Platform/app

and ran the playbook.

I haven't used Postman for anything.

**Comment by StephenOTT** [comment]
@Illusive7Man this is likely due to using Lab and 0.7.

Use tag 0.6 and use the Dev deployment (but modify it to use local rather than remote deployment).  Lab uses the latest development branch, which is not guaranteed to be stable.
See the warning at the top of this page: https://github.com/DigitalState/Platform/blob/develop/platform/documentation/environments/lab/index.md#lab-environment

**Comment by StephenOTT** [comment]
@gismomtl did you make progress using the 0.6 and Dev deployment strategy?

**Comment by gismomtl** [comment]
Hi,
yes following your advice I was able to have services available.
I'd to: use 0.6 tag, dev configuration with local deployment.
As I'd previously installed 0.7, dev, and master.. the docker images were a complete messed up.. 
even docker image prune was not sufficient... I'd to do a docker system prune -a --volumes

a great thanks for your support

**Comment by StephenOTT** [comment]
@gismomtl great!  Make sure to check out the Postman collection and the updated docs in the current develop branch for further information about the APIs!

**Comment by Illusive7Man** [comment]
Hey @gismomtl & @StephenOTT 

Could you help me configure mine to localhost because I keep getting error when establishing ssh connection. 

> fatal: [platform]: FAILED! => {"changed": true, "cmd": "ssh-copy-id -i /root/.ssh/dev/key root@127.0.0.1", "delta": "0:00:00.301490", "end": "2018-08-04 10:54:23.560483", "msg": "non-zero return code", "rc": 1, "start": "2018-08-04 10:54:23.258993", "stderr": "/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: \"/root/.ssh/dev/key.pub\"\n/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed\nexpr: warning: '^ERROR: ': using '^' as the first character\nof a basic regular expression is not portable; it is ignored\n\n/usr/bin/ssh-copy-id: ERROR: ssh: connect to host 127.0.0.1 port 22: Connection refused", "stderr_lines": ["/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: \"/root/.ssh/dev/key.pub\"", "/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed", "expr: warning: '^ERROR: ': using '^' as the first character", "of a basic regular expression is not portable; it is ignored", "", "/usr/bin/ssh-copy-id: ERROR: ssh: connect to host 127.0.0.1 port 22: Connection refused"], "stdout": "", "stdout_lines": []}

What I've done is changed in inventory.yml is **ansible_host** to 127.0.0.1
I'm not familiar with Ansible, I am not sure what I'm doing exactly. 
Windows 10

Edit:
**ansible_connection: local**, got me the same 503

**Comment by StephenOTT** [comment]
@illusive7man. What version of Windows and what version of docker are you using. You are using Windows 10 pro ?   Docker toolkit Does not work. You must have Docker for Windows, which only works with Windows pro / hyperV

**Comment by Illusive7Man** [comment]
@StephenOTT  It's Windows 10 Pro. Docker version 18.06.0-ce  (Docker for Windows)

**Comment by StephenOTT** [comment]
And to confirm: you are using Docker for Windows?  Or using Docker Toolkit?

**Comment by Illusive7Man** [comment]
@StephenOTT  [Docker for Windows](https://i.imgur.com/lrbR5eW.png)

**Comment by Illusive7Man** [comment]
I will create an issue, by tomorrow, with logs, system specifications and ansible files.
