### ISSUE TITLE
DockerFile warning

### ISSUE THREAD

**Issue by thib3113** [DigitalState/Platform#44]
When starting the platform,
Docker show up a warning, and saying this warning will nearly become a warning : 
`[WARNING]: Empty continuation line found in:
    RUN     apk --update add sudo &&     apk --update add bash &&     apk --update add --no-cache openssh &&     sed -i "s/#PermitRootLogin.*/PermitRootLogin\ yes/g" /etc/ssh/sshd_config &&     sed -i "s/#Port 22/Port 22/g" /etc/ssh/sshd_config &&     sed -i "s/#HostKey \/etc\/ssh\/ssh_host_key/HostKey \/etc\/ssh\/ssh_host_key/g" /etc/ssh/sshd_config &&     sed -i "s/#HostKey \/etc\/ssh\/ssh_host_rsa_key/HostKey \/etc\/ssh\/ssh_host_rsa_key/g" /etc/ssh/sshd_config &&     sed -i "s/#HostKey \/etc\/ssh\/ssh_host_dsa_key/HostKey \/etc\/ssh\/ssh_host_dsa_key/g" /etc/ssh/sshd_config &&     sed -i "s/#HostKey \/etc\/ssh\/ssh_host_ecdsa_key/HostKey \/etc\/ssh\/ssh_host_ecdsa_key/g" /etc/ssh/sshd_config &&     sed -i "s/#HostKey \/etc\/ssh\/ssh_host_ed25519_key/HostKey \/etc\/ssh\/ssh_host_ed25519_key/g" /etc/ssh/sshd_config &&     ssh-keygen -A &&     apk --update add python py-pip openssl ca-certificates &&     apk --update add --virtual build-dependencies python-dev libffi-dev openssl-dev build-base &&     pip install --upgrade pip cffi &&     apk --update add php7 php7-fpm &&     apk --update add php7-opcache php7-dom php7-curl php7-json php7-phar php7-openssl php7-mbstring php7-ctype php7-session php7-xml php7-xmlwriter php7-tokenizer curl &&     curl -sS https://getcomposer.org/installer | php -- --filename=composer  --install-dir=/usr/bin --version=1.0.0 &&
   composer global require "hirak/prestissimo:^0.3" &&     echo "root:root" | chpasswd &&     apk del build-dependencies &&     rm -rf /var/cache/apk/*
[WARNING]: Empty continuation lines will become errors in a future release.`

**Comment by marioprudhomme** [comment]
Fixed.
