### ISSUE TITLE
Failed at step  TASK [app/cms/container/up : Up cms container]  

### ISSUE THREAD

**Issue by yastri** [DigitalState/Platform#51]
I used  tags/0.9.1 and tried installed for lab & dev enviroment.

each enviroment failed at I used the tags/0.9.1 failed at step TASK [app/cms/container/up : Up cms container]  as below 

> TASK [include_role : app/discovery/container/up] *****************************************************************************************************************
> 
> TASK [app/discovery/container/up : Up discovery container] *******************************************************************************************************
> changed: [app]
> 
> TASK [include_role : app/formio/container/up] ********************************************************************************************************************
> 
> TASK [app/formio/container/up : Configure client host config] ****************************************************************************************************
> changed: [app]
> 
> TASK [app/formio/container/up : Configure app host config] *******************************************************************************************************
> changed: [app]
> 
> TASK [app/formio/container/up : Up formio container] *************************************************************************************************************
> changed: [app]
> 
> TASK [include_role : app/camunda/container/up] *******************************************************************************************************************
> 
> TASK [app/camunda/container/up : Up camunda container] ***********************************************************************************************************
> changed: [app]
> 
> TASK [include_role : app/cms/container/up] ***********************************************************************************************************************
> 
> TASK [app/cms/container/up : Up cms container] *******************************************************************************************************************
> fatal: [app]: FAILED! => {"changed": false, "errors": [], "module_stderr": "", "module_stdout": "4.0.8-alpine: Pulling from library/redis\n", "msg": "Error starting project error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/c2/c27f565859388a7a6b4666c7861d9a8cac3f6eec6a2fd296a39fd4895275344d/data?verify=1538026536-TH%2FLe84U3oO0%2FpVIsqxTuwL7NMA%3D: net/http: TLS handshake timeout"}
> 
> PLAY RECAP *******************************************************************************************************************************************************
> app                        : ok=126  changed=42   unreachable=0    failed=1   
> platform                   : ok=37   changed=7    unreachable=0    failed=0   
> 
> /etc/ansible/env/dev #

**Comment by marioprudhomme** [comment]
I suggest re-running the install. It seems to be a failed connection temporarily to the dockerhub image server. I seldomly run into that issue as well.

**Comment by yastri** [comment]
> I suggest re-running the install. It seems to be a failed connection temporarily to the dockerhub image server. I seldomly run into that issue as well.

thanks ..

I've already re-running.

success on-premise development, but failed on cloud.

**Comment by StephenOTT** [comment]
Also, be aware that only tag 0.6 works with the UI.  If you deploy any new tag, the portal and admin apps (the portal and admin Ui) are not fictional in those tags

**Comment by StephenOTT** [comment]
@yastri did you make progress?

**Comment by marioprudhomme** [comment]
Closed. Out of date.
