### ISSUE TITLE
Installation error DigitalState on Ubuntu 18.04 

### ISSUE THREAD

**Issue by Weglarz** [DigitalState/Platform#61]
I have a problem with installation  DiditalState Platform.
My OS is Ubuntu 18.04.
 
After the following instruction:
 
a.  git clone https://github.com/DigitalState/Platform.git
 
b.  cd Platform
c.  git checkout tags/0.13.0
 
d.  docker-compose up -d
 
e.  docker ps
 
f.  docker exec -it platform /bin/sh
 
g.  cd /etc/ansible/env/dev
 
h.  ansible-playbook ./install.yml
 
 
I received error:
TASK [Include compiled task list] ***********************************************************************************************************************************************************
included: /etc/ansible/task/app/proxy/container/up.yml for app => (item=/etc/ansible/task/app/proxy/container/up.yml)
included: /etc/ansible/task/app/discovery/container/up.yml for app => (item=/etc/ansible/task/app/discovery/container/up.yml)
included: /etc/ansible/task/app/formio/container/up.yml for app => (item=/etc/ansible/task/app/formio/container/up.yml)
included: /etc/ansible/task/app/camunda/container/up.yml for app => (item=/etc/ansible/task/app/camunda/container/up.yml)
included: /etc/ansible/task/app/records/container/up.yml for app => (item=/etc/ansible/task/app/records/container/up.yml)
included: /etc/ansible/task/app/cms/container/up.yml for app => (item=/etc/ansible/task/app/cms/container/up.yml)
included: /etc/ansible/task/app/services/container/up.yml for app => (item=/etc/ansible/task/app/services/container/up.yml)
included: /etc/ansible/task/app/assets/container/up.yml for app => (item=/etc/ansible/task/app/assets/container/up.yml)
included: /etc/ansible/task/app/cases/container/up.yml for app => (item=/etc/ansible/task/app/cases/container/up.yml)
included: /etc/ansible/task/app/authentication/container/up.yml for app => (item=/etc/ansible/task/app/authentication/container/up.yml)
included: /etc/ansible/task/app/identities/container/up.yml for app => (item=/etc/ansible/task/app/identities/container/up.yml)
included: /etc/ansible/task/app/forms/container/up.yml for app => (item=/etc/ansible/task/app/forms/container/up.yml)
 
TASK [Up proxy container] *******************************************************************************************************************************************************************
 
TASK [app/proxy/container/up : Up proxy container] ******************************************************************************************************************************************
fatal: [app]: FAILED! => {"changed": false, "errors": [], "module_stderr": "Creating dsproxy_proxy_1 ... \r\n\r\u001b[1B", "module_stdout": "1.7-alpine: Pulling from library/traefik\nDigest: sha256:930871d5e6e69c5b5d2ea7155a86ffc27d61409be8c87ccc96bc0e7250bc22c6\nStatus: Downloaded newer image for traefik:1.7-alpine\n", "msg": "Error starting project unknown cause"}
 
PLAY RECAP **********************************************************************************************************************************************************************************
app                        : ok=118  changed=33   unreachable=0    failed=1
platform                   : ok=37   changed=7    unreachable=0    failed=0
 
I try many version from 0.6.0 to last version and always  I received the same error?
 
Please help me .

**Comment by marioprudhomme** [comment]
What version docker / docker-compose ?

**Comment by Weglarz** [comment]
telemedis@telemedis:~$ docker-compose version

docker-compose version 1.22.0, build f46880fe

docker-py version: 3.4.1

CPython version: 3.6.6

OpenSSL version: OpenSSL 1.1.0f  25 May 2017

**Comment by Weglarz** [comment]
telemedis@telemedis:~$ docker version

Client:

Version:           18.06.1-ce

API version:       1.38

Go version:        go1.10.3

Git commit:        e68fc7a

Built:             Tue Aug 21 17:24:51 2018

OS/Arch:           linux/amd64

Experimental:      false

 

Server:

Engine:

  Version:          18.06.1-ce

  API version:      1.38 (minimum version 1.12)

  Go version:       go1.10.4

  Git commit:       e68fc7a

  Built:            Mon Oct  1 14:25:33 2018

  OS/Arch:          linux/amd64

  Experimental:     false

**Comment by marioprudhomme** [comment]
There are a few incompatibility issues with the latest versions of docker and docker-compose that we are working towards fixing on various OS. (`COMPOSE_CONVERT_WINDOWS_PATHS=true` was one of them among other adaptations...)

I have tested Platform and is compatible with a minimum of:

`Docker version 17.06.2-ce, build cec0b72`
`docker-compose version 1.14.0, build c7bdf9e3`
`Python 2.7.15`

However, any higher version of the above software should be considered experimental until we have upgraded, made compatible, tested and confirmed working.

Are you able to give me the output of:

`cd /srv/proxy && docker-compose up -d`

**Comment by Weglarz** [comment]
1.      Content  of cd /srv

 



 

2.      Content of  …../srv/proxy/…..



 

 

 

3.      Docker-comose uo –d

root@telemedis:/home/telemedis/DigitalState/Platform# docker-compose up -d

platform is up-to-date

app is up-to-date

**Comment by marioprudhomme** [comment]
I'm referring to manually starting the proxy container:
`cd /srv/proxy` + `docker-compose up -d`

**Comment by StephenOTT** [comment]
@Weglarz the content of your email was stripped.  Can you post it directly into github and use proper code formatting please.

**Comment by Weglarz** [comment]
Finally I installed  based on:
- Ubuntu 18.04 and 
- Docker version 17.06.2-ce, build cec0b72
- docker-compose version 1.14.0, build c7bdf9e3
- Python 2.7.15

and  I manually starting the proxy container.

I can start apps:
1. http://ui.discovery.dev.ds/ui/ds/services
2. http://api.formio.dev.ds/#/auth/login
3. http://api.camunda.dev.ds/camunda/app/admin/default/setup/#/setup

but for:
1. http://portal.dev.ds/
2. http://admin.dev.ds/
3. http://ui.proxy.dev.ds/

I receive  404 page not found

Please help help me.

**Comment by StephenOTT** [comment]
@Weglarz what tag are you using?
Portal and Admin UIs are only avaliable in v0.6 or earlier.

**Comment by Weglarz** [comment]
It is possible to use all components  in one installation?
What is instruction for this case?
When will be all components in the same version?
There is road map for DigitalState?
Id like use this platform for telemedicine systems adding another components like IoT - it is possible?
Please inform me as You can.

**Comment by StephenOTT** [comment]
>It is possible to use all components in one installation?
>What is instruction for this case?
>When will be all components in the same version?

Yes: but if you are looking to use the UI, then you will need to be with v0.6.  Newer features have been added in subsequent builds, but the UI has not been maintained until the updates stabilize (do not have a time estimate atm).


>roadmap

The next large feature we are rolling out for DS is a update to the internals of DS microservices that use Api-platform.com.  This is ongoing at the moment.

>Id like use this platform for telemedicine systems adding another components like IoT - it is possible?

You could add the components as you see fit with the api-platform.com framework or using Camunda as a integration point.  Example you could collect data from IOT devices that go into a queue and have camunda process the queue: such as a doctor reviewing results submitted by a patient.

**Comment by Weglarz** [comment]
When I setup v0.6 and run installation the following   errors  was generated:
root@telemedisdom:/home/telemedis/DigitalState/Platform# git checkout tags/0.6.0
Note: checking out 'tags/0.6.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 0c860a35 Update version file
root@telemedisdom:/home/telemedis/DigitalState/Platform# docker-compose up -d
WARNING: Found orphan containers (app) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Recreating platform ... done
root@telemedisdom:/home/telemedis/DigitalState/Platform# docker exec -it platform /bin/sh
/etc/ansible/env/lab # cd /etc/ansible/env/dev
/etc/ansible/env/dev # ansible-playbook ./install.yml

PLAY [Create ssh private and public keys] ***************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************
ok: [platform]

TASK [Check if the ssh private key exists] **************************************************************************************************************************************************
ok: [platform]

TASK [Create ssh private key] ***************************************************************************************************************************************************************
skipping: [platform]

PLAY [Create jwt private and public keys] ***************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************
ok: [platform]

TASK [Check if the jwt private key exists] **************************************************************************************************************************************************
ok: [platform]

TASK [Create jwt private key] ***************************************************************************************************************************************************************
fatal: [platform]: FAILED! => {"changed": true, "cmd": "openssl genrsa -out /root/resource/jwt/dev/key -aes256 -passout pass: 4096", "delta": "0:00:00.376510", "end": "2018-11-22 09:55:34.752172", "msg": "non-zero return code", "rc": 1, "start": "2018-11-22 09:55:34.375662", "stderr": "Generating RSA private key, 4096 bit long modulus\n...++++\n...............................................................................++++\ne is 65537 (0x10001)\n139773251595212:error:0906906F:PEM routines:PEM_ASN1_write_bio:read key:pem_lib.c:373:", "stderr_lines": ["Generating RSA private key, 4096 bit long modulus", "...++++", "...............................................................................++++", "e is 65537 (0x10001)", "139773251595212:error:0906906F:PEM routines:PEM_ASN1_write_bio:read key:pem_lib.c:373:"], "stdout": "", "stdout_lines": []}

PLAY RECAP **********************************************************************************************************************************************************************************
platform                   : ok=4    changed=0    unreachable=0    failed=1



What is wrong in my installation?

**Comment by StephenOTT** [comment]
There are some major updates rolling out in the next few weeks that will simplify your needs.  If you can wait for this, I would recommend you would wait.  

cc: @marioprudhomme

**Comment by Weglarz** [comment]
Hi,
I do'nt see new version?
Will be lunched in this year?
I need enterprise version with formio and comunda integrated.
Regards
Wladyslaw Weglarz
Telemedis

**Comment by marioprudhomme** [comment]
We are aiming for first week of January for the major upgrades.

This includes latest version of symfony, api-platform, simplification refactor and brings us closer to a factor-12 app.

**Comment by Weglarz** [comment]
Thank You for quick answer

**Comment by Weglarz** [comment]
Hi

What is the status of upgrades DigitalState?

When will be launched new version with the major upgrades?

Regards

Wladyslaw Weglarz

Telemedis

**Comment by marioprudhomme** [comment]
My personal timeline was actually today, but I'll have to push it to hopefully next week. 

We ran into various issues, ranging from incompatibilities with composer package versions, Symfony 4 and Api Platform 2.3, among other things, which in some cases required full re-write of some pieces of code or swapping vendor packages.

I can say the bulk of the work has been done. I'm in the final stages of writing behat tests, confirming no backward breaks and testing inter-microservice communication working accordingly, etc.

**Comment by Weglarz** [comment]
Thank You for info

**Comment by Weglarz** [comment]
Hi

Please inform me when will be launched full consolidated version DigitalState Platform ?

 

Regards

Władysław Węglarz

Telemedis

**Comment by Weglarz** [comment]
Hi

Have you some news about new consolidated version DigitalState Platform?

Regards

Władysław Węglarz

Telemedis

**Comment by Weglarz** [comment]
Please update me  about new  purchase  date of the DigitalState?
It is very important  for me !
Regards

**Comment by marioprudhomme** [comment]
We are aiming for the new release this week if everything goes well.

**Comment by marioprudhomme** [comment]
The release is ready to be tagged. We are simply waiting for feedback from
our clients to make sure there are no surprises. But overall good news :)

**Comment by StephenOTT** [comment]
@Weglarz did you have a chance to test?

**Comment by Weglarz** [comment]
Hi Stephen,
I tray install locally on my mac laptop and ubuntu server.
Installation failed in both cases.
Step installation is following:
1.  cd C:\Users\Demo
2.  git clone https://github.com/DigitalState/Platform.git
3.  cd Platform
4. docker-compose up -d
5. docker exec -it platform /bin/sh
6. cd /etc/ansible/env/dev
7. ansible-playbook ./install.yml

The log from installation  is attached
[installation_log.txt](https://github.com/DigitalState/Platform/files/2836268/installation_log.txt)

Please give me support

Did you chance to verify installation problems last version ?

**Comment by Weglarz** [comment]
I want to install latest version DigitalState Platform - what should I use 

git checkout tags/0.x.x

?

Please give me support

**Comment by Weglarz** [comment]
Hi Stephen,
I still hAVe a probldm with installation.
I send log file from installation to Mario.
Please help me.
Regards
Władysław Węglarz
Telemedis

**Comment by marioprudhomme** [comment]
Create a gist of your stacktrace error logs or paste it inline here

**Comment by Weglarz** [comment]
Installation failed:
last  tasks:
TASK [Include compiled task list] ***********************************************************************************************************************************************************
included: /etc/ansible/task/app/proxy/container/up.yml for app => (item=/etc/ansible/task/app/proxy/container/up.yml)
included: /etc/ansible/task/app/discovery/container/up.yml for app => (item=/etc/ansible/task/app/discovery/container/up.yml)
included: /etc/ansible/task/app/formio/container/up.yml for app => (item=/etc/ansible/task/app/formio/container/up.yml)
included: /etc/ansible/task/app/camunda/container/up.yml for app => (item=/etc/ansible/task/app/camunda/container/up.yml)
included: /etc/ansible/task/app/services/container/up.yml for app => (item=/etc/ansible/task/app/services/container/up.yml)
included: /etc/ansible/task/app/forms/container/up.yml for app => (item=/etc/ansible/task/app/forms/container/up.yml)
included: /etc/ansible/task/app/cases/container/up.yml for app => (item=/etc/ansible/task/app/cases/container/up.yml)
included: /etc/ansible/task/app/assets/container/up.yml for app => (item=/etc/ansible/task/app/assets/container/up.yml)
included: /etc/ansible/task/app/identities/container/up.yml for app => (item=/etc/ansible/task/app/identities/container/up.yml)
included: /etc/ansible/task/app/records/container/up.yml for app => (item=/etc/ansible/task/app/records/container/up.yml)
included: /etc/ansible/task/app/authentication/container/up.yml for app => (item=/etc/ansible/task/app/authentication/container/up.yml)
included: /etc/ansible/task/app/cms/container/up.yml for app => (item=/etc/ansible/task/app/cms/container/up.yml)

TASK [Up proxy container] *******************************************************************************************************************************************************************

TASK [app/proxy/container/up : Up proxy container] ******************************************************************************************************************************************
changed: [app]

TASK [Up discovery container] ***************************************************************************************************************************************************************

TASK [app/discovery/container/up : Up discovery container] **********************************************************************************************************************************
changed: [app]

TASK [Retrieve proxy container ip] **********************************************************************************************************************************************************
included: /etc/ansible/task/app/proxy/container/property/ip.yml for app

TASK [Obtain proxy container ip] ************************************************************************************************************************************************************
changed: [app]

TASK [Up formio container] ******************************************************************************************************************************************************************

TASK [app/formio/container/up : Configure client host config] *******************************************************************************************************************************
changed: [app]

TASK [app/formio/container/up : Configure app host config] **********************************************************************************************************************************
changed: [app]

TASK [app/formio/container/up : Up formio container] ****************************************************************************************************************************************
changed: [app]

TASK [Retrieve proxy container ip] **********************************************************************************************************************************************************
included: /etc/ansible/task/app/proxy/container/property/ip.yml for app

TASK [Obtain proxy container ip] ************************************************************************************************************************************************************
changed: [app]

TASK [Up camunda container] *****************************************************************************************************************************************************************

TASK [app/camunda/container/up : Up camunda container] **************************************************************************************************************************************
changed: [app]

TASK [Retrieve proxy container ip] **********************************************************************************************************************************************************
included: /etc/ansible/task/app/proxy/container/property/ip.yml for app

TASK [Obtain proxy container ip] ************************************************************************************************************************************************************
changed: [app]

TASK [Up services container] ****************************************************************************************************************************************************************

TASK [app/services/container/up : Up services container] ************************************************************************************************************************************
changed: [app]

TASK [app/services/container/up : Waiting for services container to finalize installation] **************************************************************************************************
FAILED - RETRYING: Waiting for services container to finalize installation (60 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (59 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (58 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (57 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (56 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (55 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (54 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (53 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (52 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (51 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (50 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (49 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (48 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (47 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (46 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (45 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (44 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (43 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (42 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (41 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (40 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (39 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (38 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (37 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (36 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (35 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (34 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (33 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (32 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (31 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (30 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (29 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (28 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (27 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (26 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (25 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (24 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (23 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (22 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (21 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (20 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (19 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (18 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (17 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (16 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (15 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (14 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (13 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (12 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (11 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (10 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (9 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (8 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (7 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (6 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (5 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (4 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (3 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (2 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (1 retries left).
fatal: [app]: FAILED! => {"attempts": 60, "changed": false, "cmd": "docker-compose exec -T php pidof php-fpm | cat", "delta": "0:00:00.441914", "end": "2019-02-12 11:26:50.068364", "rc": 0, "start": "2019-02-12 11:26:49.626450", "stderr": "No container found for php_1", "stderr_lines": ["No container found for php_1"], "stdout": "", "stdout_lines": []}

PLAY RECAP **********************************************************************************************************************************************************************************
app                        : ok=131  changed=43   unreachable=0    failed=1
platform                   : ok=37   changed=7    unreachable=0    failed=0




 **Platfrom**

UBUNTU 18.04

**Docker version**
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Fri Oct 19 19:43:14 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Thu Sep 27 02:39:50 2018
  OS/Arch:          linux/amd64
  Experimental:     false

 **docker-compose version**
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

**Comment by Weglarz** [comment]
Did you receive description my  installation issue  ?

Please give me support
