### ISSUE TITLE
Installation procedure failed

### ISSUE THREAD

**Issue by Weglarz** [DigitalState/Platform#72]
Hi Mario,

Ubuntu 19.04

docker version
Client:
Version:           18.06.1-ce
API version:       1.38
Go version:        go1.10.1
Git commit:        e68fc7a
Built:             Fri Jan 25 14:33:51 2019
OS/Arch:           linux/amd64
Experimental:      false

Server:
Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Thu Sep 27 02:39:50 2018
  OS/Arch:          linux/amd64
  Experimental:     false

docker-compose version
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

Stacktrace – last sentence:
TASK [Include compiled task list] ***********************************************************************************************************************************************************
included: /etc/ansible/task/app/proxy/container/up.yml for app => (item=/etc/ansible/task/app/proxy/container/up.yml)
included: /etc/ansible/task/app/discovery/container/up.yml for app => (item=/etc/ansible/task/app/discovery/container/up.yml)
included: /etc/ansible/task/app/formio/container/up.yml for app => (item=/etc/ansible/task/app/formio/container/up.yml)
included: /etc/ansible/task/app/camunda/container/up.yml for app => (item=/etc/ansible/task/app/camunda/container/up.yml)
included: /etc/ansible/task/app/services/container/up.yml for app => (item=/etc/ansible/task/app/services/container/up.yml)
included: /etc/ansible/task/app/forms/container/up.yml for app => (item=/etc/ansible/task/app/forms/container/up.yml)
included: /etc/ansible/task/app/cases/container/up.yml for app => (item=/etc/ansible/task/app/cases/container/up.yml)
included: /etc/ansible/task/app/assets/container/up.yml for app => (item=/etc/ansible/task/app/assets/container/up.yml)
included: /etc/ansible/task/app/identities/container/up.yml for app => (item=/etc/ansible/task/app/identities/container/up.yml)
included: /etc/ansible/task/app/records/container/up.yml for app => (item=/etc/ansible/task/app/records/container/up.yml)
included: /etc/ansible/task/app/authentication/container/up.yml for app => (item=/etc/ansible/task/app/authentication/container/up.yml)
included: /etc/ansible/task/app/cms/container/up.yml for app => (item=/etc/ansible/task/app/cms/container/up.yml)

TASK [Up proxy container] *******************************************************************************************************************************************************************

TASK [app/proxy/container/up : Up proxy container] ******************************************************************************************************************************************
changed: [app]

TASK [Up discovery container] ***************************************************************************************************************************************************************

TASK [app/discovery/container/up : Up discovery container] **********************************************************************************************************************************
changed: [app]

TASK [Retrieve proxy container ip] **********************************************************************************************************************************************************
included: /etc/ansible/task/app/proxy/container/property/ip.yml for app

TASK [Obtain proxy container ip] ************************************************************************************************************************************************************
changed: [app]

TASK [Up formio container] ******************************************************************************************************************************************************************

TASK [app/formio/container/up : Configure client host config] *******************************************************************************************************************************
changed: [app]

TASK [app/formio/container/up : Configure app host config] **********************************************************************************************************************************
changed: [app]

TASK [app/formio/container/up : Up formio container] ****************************************************************************************************************************************
changed: [app]

TASK [Retrieve proxy container ip] **********************************************************************************************************************************************************
included: /etc/ansible/task/app/proxy/container/property/ip.yml for app

TASK [Obtain proxy container ip] ************************************************************************************************************************************************************
changed: [app]

TASK [Up camunda container] *****************************************************************************************************************************************************************

TASK [app/camunda/container/up : Up camunda container] **************************************************************************************************************************************
changed: [app]

TASK [Retrieve proxy container ip] **********************************************************************************************************************************************************
included: /etc/ansible/task/app/proxy/container/property/ip.yml for app

TASK [Obtain proxy container ip] ************************************************************************************************************************************************************
changed: [app]

TASK [Up services container] ****************************************************************************************************************************************************************

TASK [app/services/container/up : Up services container] ************************************************************************************************************************************
changed: [app]

TASK [app/services/container/up : Waiting for services container to finalize installation] **************************************************************************************************
FAILED - RETRYING: Waiting for services container to finalize installation (60 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (59 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (58 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (57 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (56 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (55 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (54 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (53 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (52 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (51 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (50 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (49 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (48 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (47 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (46 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (45 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (44 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (43 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (42 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (41 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (40 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (39 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (38 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (37 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (36 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (35 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (34 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (33 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (32 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (31 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (30 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (29 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (28 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (27 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (26 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (25 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (24 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (23 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (22 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (21 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (20 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (19 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (18 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (17 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (16 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (15 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (14 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (13 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (12 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (11 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (10 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (9 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (8 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (7 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (6 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (5 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (4 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (3 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (2 retries left).
FAILED - RETRYING: Waiting for services container to finalize installation (1 retries left).
fatal: [app]: FAILED! => {"attempts": 60, "changed": false, "cmd": "docker-compose exec -T php pidof php-fpm | cat", "delta": "0:00:00.439817", "end": "2019-02-13 12:47:40.714486", "rc": 0, "start": "2019-02-13 12:47:40.274669", "stderr": "No container found for php_1", "stderr_lines": ["No container found for php_1"], "stdout": "", "stdout_lines": []}

PLAY RECAP **********************************************************************************************************************************************************************************
app                        : ok=131  changed=43   unreachable=0    failed=1
platform                   : ok=37   changed=7    unreachable=0    failed=0

Please give me support

**Comment by StephenOTT** [comment]
@Weglarz please act with a level of decorum.

You have opened multiple duplicate issues; this does not move the issue any faster.

This is a open source project with multiple initiatives and work streams.  if @marioprudhomme has not answered it is because of other priorities at the moment, but rest assured that someone has seen the issue.

with 0.15 there is a issue on some deployments: https://github.com/DigitalState/Platform/issues/70.

You have already commented multiple times.  Please follow along with that issue
