### ISSUE TITLE
skipping error, fatal: [platform]: FAILED! => {"changed": true, "cmd": "openssl genrsa -out /root/resource/jwt/dev/key -aes256 -passout pass: 4096

### ISSUE THREAD

**Issue by valentininua** [DigitalState/Platform#86]
I follow the instructions step by step

https://github.com/DigitalState/Platform/blob/develop/platform/documentation/environments/dev/index.md

git clone https://github.com/DigitalState/Platform.git
cd Platform
git checkout tags/0.17.0 

docker-compose up -d --no-deps --build

docker exec -it platform /bin/sh

getting an error

![1](https://user-images.githubusercontent.com/9616622/67964304-1b0d2280-fc11-11e9-9007-deb0133ffc51.png)

**Comment by valentininua** [comment]
git checkout tags/0.6.0 

![Screenshot 2019-10-31 at 19 30 50](https://user-images.githubusercontent.com/9616622/67966565-282c1080-fc15-11e9-8b17-c2a816aef09f.png)

**Comment by valentininua** [comment]
we are trying to use the    ansible-playbook -i inventory.yml ./install.yml     command

got error 
![Screenshot 2019-10-31 at 19 38 59](https://user-images.githubusercontent.com/9616622/67967334-7c83c000-fc16-11e9-8d68-4f49de07fd14.png)

**Comment by valentininua** [comment]
the problem is solved when using **Ubuntu**

**Comment by thib3113** [comment]
@valentininua what did you use before ? 
Docker for windows ? ( with toolbox, or something like that ? )

**Comment by valentininua** [comment]
I used CentOS , MacOS  - got error.
if using Ubuntu  18 - all ok 
and run this **ansible-playbook -i inventory.yml ./install.yml**
