### ISSUE TITLE
Error when running ansible-playbook jwt/configure.yml

### ISSUE THREAD

**Issue by baddlan** [DigitalState/Platform#9]
From within the SDK container, when doing `ansible-playbook jwt/configure.yml` after all the other steps:

```
fatal: [server]: FAILED! => {"changed": false, "failed": true, "msg": "Destination /srv/authentication/app/config/parameters.yml does not exist !", "rc": 257}
```

The path `/srv/authentication/` does not actually exist in the Auth container.

**Comment by marioprudhomme** [comment]
Problem is when ansible runs docker-compose up on authentication, the ansible task completes and moves on to the next task while the authentication container continues installing composer packages. 

The jwt/configure task runs before composer creates the parameters.yml file.

Will have to look into a fix.

**Comment by StephenOTT** [comment]
@mario-digitalstate you could use http://docs.ansible.com/ansible/latest/wait_for_module.html and wait for a host to resolve

**Comment by marioprudhomme** [comment]
Fixed by making ansible wait while the container finishes composer installation.
